
spring:
  application:
    name: memoryBox_external
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_SERVER:165.192.105.57}:${DB_PORT:30135}/${DB_NAME:memory_box}?useUnicode=true&characterEncoding=utf-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      connection-timeout: 5000
      validation-timeout: 1000
      maximum-pool-size: 30
      minimum-idle: 2
      connection-test-query: SELECT 1
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

#swagger
springdoc:
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /swagger.html
    enabled: true
    operationsSorter: alpha
    disable-swagger-default-url: true
    display-request-duration: true    #try it out ?? ? request duration ? ??? ???
    doc-expansion : none    # api?? ?? ???
  #    groups-order: DESC
  api-docs:
    enabled: true
    path: /api-docs